export enum Genre {
    Action = "Action",
    Comedy = "Comedy",
    Drama = "Drama",
    Fantasy = "Fantasy",
    Horror = "Horror",
    Mystery = "Mystery",
    Romance = "Romance",
    Thriller = "Thriller",
    SciFi = "SciFi",
    Crime = "Crime",
    Adventure = "Adventure",
    Animation = "Animation",
    Family = "Family",
    History = "History",
    War = "War",
    Western = "Western",
    Documentary = "Documentary",
    Music = "Music",
    Sport = "Sport",
    Biography = "Biography",
    Musical = "Musical",
    News = "News",
    RealityTV = "RealityTV",
    TalkShow = "TalkShow",
    GameShow = "GameShow",
    Short = "Short"
}