export enum Genre {
    Action = "Action",
    Adventure = "Adventure",
    Animation = "Animation",
    Biography = "Biography",
    Comedy = "Comedy",
    Crime = "Crime",
    Documentary = "Documentary",
    Drama = "Drama",
    Family = "Family",
    Fantasy = "Fantasy",
    History = "History",
    Horror = "Horror",
    Music = "Music",
    Musical = "Musical",
    Mystery = "Mystery",
    Romance = "Romance",
    SciFi = "SciFi",
    Sport = "Sport",
    Thriller = "Thriller",
    War = "War",
    Western = "Western",
}